package com.guga;

import io.javalin.Javalin;

public class AppConfigureServer {

    public static void main(String[] args) {
        Javalin.create()
            .contextPath("/context-path")
            .enableAutogeneratedEtags()
            .enableCorsForOrigin("*")
            .enableDebugLogging()
            .enableStaticFiles("/public")
            .start();
    }
}
